version: '3'
services:
  ros:
    build: ./
    volumes:
      - ./workspace:/home/user/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    privileged: true
    network_mode: "host"
    ipc: host
    pid: host
    environment:
      # set DISPLAY environment variable
      - DISPLAY=${DISPLAY}


